#     copy : from https://github.com/G-Node/nix-java/blob/master/appveyor.yml
#      doc : https://linuxtut.com/en/1b97b0d36c81785522a8/
# software : https://www.appveyor.com/docs/windows-images-software/#java

# Branches

branches:
  only:
  - master
image: ubuntu

# version: 0.1.{build}
# os: Visual Studio 2014 CTP4

environment:
  matrix:
  # 64 bit
  - PLATFORM: x64
    CONFIGURATION: Release
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    RDP: "no"

install:
  - set PATH=%PATH%

build_script:

  # Build Java
  - cd maven
  - mvn clean install -Dmaven.test.failure.ignore=true -Dplatform.dependency=false

on_failure:

  # Display error log file if generated
  - if exist *.log type *.log

test_script: []
